OWASP/SecureTea-Project

- SecureTea.py
**Changes this pull request makes :**
Fixes : #12 
**Checklist :**
```
Python : 3.6.5
OS : Ubuntu 18.04.1 LTS
```
> Fix pm-suspend in new releases of Ubuntu

- setup.py
**Changes this pull request makes :**
Fixes  #9 
**Checklist :** 
```
Python : 3.6.5
OS : Ubuntu 18.04.1 LTS
```
> Fix #9 setup error

- .gitignore
References #15 
`Changes this pull request makes:`
Updates `.gitignore` to exclude the files/directories created on compiling.
Checklist :
**Development environment**
```
Python : 2.7
OS : Ubuntu 18.04.1 LTS
```
> minor updates to .gitignore

- .gitignore
> Fix Gitinore

- securetea/arguments.py
- securetea/core.py
- securetea/secureTeaTelegram.py
- securetea/secureTeaTwilio.py
- securetea/secureTeaTwitter.py
- setup.py
**READY**
Fix a few code lint warnings.
> Fix code lint warnings

- securetea.conf
- securetea/common.py
- securetea/secureTeaSlack.py
- securetea/secureTeaTelegram.py
- securetea/secureTeaTwilio.py
- securetea/secureTeaTwitter.py
**READY**
Move common methods to new file
> Move common methods to new file

- securetea.conf
- securetea/args_helper.py
- securetea/arguments.py
- securetea/core.py
This PR adds `args_helper.py` module, which handles all the argument parsing task, hence `core.py` is less crowded.
**Features added** :
1. User can now setup their credentials in an interactive manner, i.e. a wizard setup mode.
For example : `sudo python SecureTea.py --twitter` will start an interactive mode, where users need to input their token details one after the other.
```
Usage : 
--twitter       Setup twitter credentials
--twilio_sms    Setup twilio credentials 
--telegram      Setup telegram credentials
```
2. User can also setup all the notification medium at one go, by using `--all` argument.
Example : `sudo python SecureTea.py --all`
3. Earlier Twitter was compulsory, now no particular medium is compulsory, user can abide by any medium.
OS: Ubuntu 18.04 LTS
Python Version: …
> Reduce code crowding in core.py & introduce interactive setup

- README.md
- securetea/args_helper.py
- securetea/common.py
- securetea/core.py
- securetea/secureTeaSlack.py
- securetea/secureTeaTelegram.py
- securetea/secureTeaTwilio.py
- securetea/secureTeaTwitter.py
**READY**
- Common functions moved to `common.py`
- Codacy issues corrected
- Fixed typos
- Fixed `README.md` typos, minor changes & added badges
None
None
None
None
> Minor touchups

- securetea/lib/firewall/README.md
- securetea/lib/firewall/firewall_monitor.py
- test/test_common.py
- test/test_configurations.py
- test/test_firewall_monitor.py
- test/test_secureTeaSlack.py
- test/test_secureTeaTwilio.py
- test/test_secureTeaTwitter.py
**READY**
Add unit-test cases for the uncovered functions.
**Details:**
- Test cases for all the remaining uncovered functions that can be covered.
- Edge cases are carefully taken care of.
- All external services and API calls are mocked.
- Test & functional independence is taken care of, such that no two function, test interfere with each other.
None
None
`sudo python3 -m unittest`
Test Cases
> Add unit-tests

- README.md
- doc/dev_guide.md
- doc/user_guide.md
**READY**
Separate developer & user guide.
None
branch | PR
None
```sh
```
1. `/doc/dev_guide.md`
2. `README.md`
> Separate developer & user guide

- README_jp.md
> First Created

- .github/ISSUE_TEMPLATE/bug_report.md
There was some wrong things written for example iOS was mentioned a desktop system,etc.Fixing it.
**READY**
wrong OS name mentioned for desktop
Nothing
Updation with current trends and relevant devices
> Updated bug report file

- .github/ISSUE_TEMPLATE/feature_request.md
> Minor changes

- requirements.txt
- securetea/common.py
- securetea/lib/notifs/secureTeaSlack.py
- securetea/lib/notifs/secureTeaTelegram.py
- securetea/lib/notifs/secureTeaTwilio.py
- securetea/lib/notifs/secureTeaTwitter.py
- test/test_common.py
- test/test_secureTeaTwilio.py
**READY**
Add geo-location function that returns the current location using IP.
Connected all the notification with this new update, i.e. all of them are sending messages with location now.
None
branch | PR
None
```sh
```
- `test_common.py`
- `common.py`
- `requirements.txt`
- `secureTeaTwilio.py`
- `secureTeaSlack.py`
- `secureTeaTwitter.py`
- `secureTeaTelegram.py`
**Twitter notification:**
> Add geo-location function

- securetea.conf
- securetea/__init__.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/core.py
- securetea/lib/__init__.py
- securetea/lib/security_header/__init__.py
- securetea/lib/security_header/secureTeaHeaders.py
- test/test_secureTeaHeaders.py
**READY**
Look for insecure headers by sending requests to the URL, the following features are added:
- Insecure headers
1. X-XSS-Protection
2. X-Content-Type
3. Strict Transport Security
4. Content Security Policy
5. X-Frame
- HTTP methods
1. Test all methods
2. Cross Site Tracing vulnerability
- Check for cookie details
None
branch | PR
None
**Using CLI**
`sudo python SecureTea.py --insecure_headers --url <url name>`
**Using interactive setup**
`sudo python SecureTea.py --insecure_headers`
```sh
```
Addition: `secureTeaHeaders.py`
- `securetea.conf`
- `core.py`
- `args_helper.py`
- `arguments.py`
**Running in debug mode:**
> Add insecure-headers feature

- README.md
> following atx in readme.md

- doc/en-US/README_backup.md
- doc/en-US/dev_guide.md
- doc/hi-IN/README.md
**READY**
branch | PR
```sh
```
1. 
*
> following atx

- doc/hi-IN/README.md
> Minor fixes

- doc/en-US/README_backup.md
- doc/en-US/dev_guide.md
- doc/ja-JP/README.md
branch | PR
- [ x] Documentation
> Update Docs tags in jp-Jp

- doc/en-US/user_guide.md
**READY**
I added AWS-SES documentation.
https://github.com/OWASP/SecureTea-Project/pull/70
Please if the arguments list is correct or not.
```sh
```
1. 
List general components of the application that this PR will affect: AWS-SES feature(part of email)
> AWS-SES documentaion added.

- README.md
> Fix footer in root Readme

- doc/en-US/dev_guide.md
> added aws to roadmap and minor correction

- doc/en-US/user_guide.md
> Updated user guide

- doc/Integration_list/List_integration.md
**READY/**
As per discussion, here is the raw list. Will add web links soon.
> Added integration_list for roadmap.

- doc/en-US/user_guide.md
- securetea.conf
- securetea/__init__.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/core.py
- securetea/lib/__init__.py
- securetea/lib/notifs/__init__.py
- securetea/lib/notifs/secureTeaGmail.py
- test/test_secureTeaGmail.py
**READY**
Closes #36 
Add Gmail notification feature.
The issue was open for quite a few days, hence decided to close it.
None
branch | PR
None
1. Interactive mode
```sh
sudo python3 SecureTea.py --gmail
sudo python2 SecureTea.py --gmail
```
```sh
sudo python3 SecureTea.py
sudo python2 SecureTea.py
```
2. Using arguments
```sh
sudo python3 SecureTea.py --sender_email <data> password <data> --to_email <data>
sudo python2 SecureTea.py --sender_email <data> password <data> --to_email <data>
```
- `secureTeaGmail.py`
- `test_secureTeaGmail.py`
- `core.py`
- `args_helper.py`
- `arguments.py`
**Sample output**
> Add Gmail notification feature

- SecureTea.py
- monitor.py
- securetea/lib/notifs/aws/helper_email.py
- securetea/lib/notifs/aws/secureTeaAwsSES.py
- securetea/logger.py
**READY**
PEP-8 fixes and other minor touchups.
None
branch | PR
```sh
```
- `secureTeaAwsSES.py`
- `helper_email.py`
- `SecureTea.py`
- `logger.py`
- `monitor.py`
> PEP-8 & other minor fixes

- requirements.txt
- securetea/logger.py
**READY**
Close #52 
Ran into this problem while trying to install SecureTea on my newly installed Parrot VM. Here's a quick fix for the problem.
branch | PR
None
```sh
```
`logger.py`
> Fix #52 - sqlite3 operational error

- doc/en-US/user_guide.md
Add libnetfilterqueue to pre-requisites.
**READY**
Update pre-requisites. (user guide)
branch | PR
```sh
```
1. 
*
> Add libnetfilterqueue to pre-requisites

- README.md
> Added Youtube link

- securetea/core.py
- securetea/lib/notifs/aws/helper_email.py
- securetea/lib/notifs/aws/secureTeaAwsSES.py
- securetea/lib/notifs/secureTeaGmail.py
- securetea/lib/notifs/secureTeaSlack.py
- securetea/lib/notifs/secureTeaTelegram.py
- securetea/lib/notifs/secureTeaTwilio.py
- securetea/lib/notifs/secureTeaTwitter.py
- securetea/logger.py
**READY**
- Added proper docstrings
- Fixed typos
- Brought uniformity in docstring style
- Added comments to facilitate easy understanding of the code base for new contributors 
None
branch | PR
```sh
```
*
> Add docstrings to un-documented functions/methods

- securetea.conf
- securetea/__init__.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/core.py
- securetea/lib/__init__.py
- securetea/lib/ids/__init__.py
- securetea/lib/ids/recon_attack.py
- securetea/lib/ids/secureTeaIDS.py
- test/test_recon_attack.py
**READY**
Detect probe (**reconnaissance**) attacks (performed for information gathering)
- General scans: TCP ACK & TCP Window, UDP, ICMP scans
- Stealth scans: FIN, XMAS, NULL scans
- OS fingerprinting scans
branch | PR
```sh
sudo python3 SecureTea.py --debug --ids
```
- **Nmap command for FIN scan:** `nmap -sF -T4 10.0.2.15`
- **Attack replication setup:**
2 Kali Linux VMs connected to each other in a NAT network.
```
Host machine OS: Ubuntu 18.04 LTS …
```
> Add SecureTea IDS (recon)

- doc/en-US/dev_guide.md
- doc/en-US/user_guide.md
**READY**
Update user and developer guide.
branch | PR
```sh
```
1. SecureTea Docs
> Update docs (user & dev guide)

- doc/en-US/dev_guide.md
- doc/en-US/user_guide.md
**READY**
- Added missing details
- Updated Firewall feature details
- Updated Insecure headers feature details
- Updated Roadmap as per GSoC proposal (roughly in the same sequential order)
branch | PR
```sh
```
1. User guide
2. Developer guide
> Update user & developer guide

- setup.py
**READY**
**Changes made:**
- Updated install requirements.
- Updated long description readme.
- Updated to exclude test cases.
- Added classifiers.
- Added python version requirements.
**Works smoothly on:**
1. Ubuntu 18.04 LTS
2. Kali 2018.2
branch | PR
```sh
sudo python setup.py --help
sudo python setup.py install
```
1. `setup.py`
> Update setup.py to latest

- setup.py
> Fix typo and project url

- setup.py
**READY**
- Perform a dependency check before proceeding with the installation.
- To add a new dependency in future, we will just need to update the `DEPENDENCY_COMMAND_MAP`. Rest will be handled.
branch | PR
```sh
sudo python3 setup.py install
```
1. `setup.py`
> Update to setup.py to check for dependency

- setup.py
**READY**
- Enable OS specific dependency installation
- Display message if OS not in listing & continue with the rest.
branch | PR
```sh
```
1. 
*
> Enable OS specific dependency installation

- setup.py
> Update version number and formatting

- .travis.yml
> Add Travis CI build config file for building and deploying to PyPi

- .travis.yml
> Add skip existing option in PyPi deploy configuration for Travis CI

- .teleNotify.sh
- .travis.yml
> Add telegram notification for CI builds

- .travis.yml
- securetea/logger.py
- test/test_configurations.py
> Fix pytest travis error

- .travis.yml
- README.md
> Fix travis build error while running pytest

- .teleNotify.sh
> Update notification template for build notification

- doc/en-US/dev_guide.md
**READY**
- Add system log developer guide:
- Current OS and log parsing support
- Current features
- Guide to extend support for various variants
branch | PR
```sh
```
1. `dev_guide.md`
> Add system log developer guide

- securetea.conf
**READY**
Fixes #129 
branch | PR
```sh
```
1. `securetea.conf`
> Fix #129 AWS SES KeyError

- securetea/lib/notifs/secureTeaGmail.py
**READY**
Fix #131 - Initialize before destruct.
branch | PR
```sh
```
1. 
1. `secureTeaGmail.py`
> Fix #131 - Initialize before destruct

- securetea/logger.py
**READY**
- **Fix Codacy warning** - Handle exception in `logger.py`.
branch | PR
```sh
```
1. `logger.py`
> Fix Codacy warning - Handle exception

- doc/en-US/user_guide_pypi.md
**READY**
Create user guide for PyPi markdown support.
- PyPi won't allow internal hyperlinks, hence internal page links are removed.
- All the external links are kept intact, since they are very much supported.
- PyPi can allow images to be present in the readme, condition being the image has a complete raw url, not a relative URL, which was the case previously. All image links have been converted to raw links.
**Refrence -** https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github
branch | PR
Outline the steps to test or reproduce …
> Create user guide for PyPi

- doc/en-US/user_guide.md
**READY**
- Updates `user_guide.md` to add system log monitor details.
- Fixes some typos
branch | PR
```sh
```
> Update user docs to add system log monitor

- README.md
> Update readme with logo

- README.md
> Update Readme heading

- doc/en-US/user_guide.md
**READY**
- Add server log features & usage details.
- Remove SQLite DB details as of deprecation.
branch | PR
```sh
```
> Add server log documentation (user)

- doc/en-US/user_guide_pypi.md
**READY**
- Add server log features & usage details.
- Remove SQLite DB details as of deprecation.
branch | PR
```sh
```
> Add server log docs (PyPi)

- setup.py
**READY**
Update setup.py for v1.4 release.
branch | PR
```sh
```
1. 
*
> Update setup.py for v1.4 release

- doc/en-US/user_guide.md
**READY**
Classify arguments for easier understanding.
branch | PR
```sh
```
> Classify arguments for easier understanding

- securetea/lib/ids/secureTeaIDS.py
**READY**
- Display list of interfaces.
- The result is beautifully parsed.
- User can select the index number of the interface.
branch | PR
```sh
sudo python3 SecureTea.py --ids --debug
sudo python3 SecureTea.py --firewall --debug
```
1. `secureTeaIDS.py`
> Display list of interfaces

- doc/en-US/user_guide.md
**READY**
Update user docs for auto-server-patcher.
branch | PR
```sh
```
> Update user docs for auto-server-patcher

- doc/en-US/user_guide_pypi.md
**READY**
Update PyPi user guide for auto-server-patcher & tabular view of arguments.
branch | PR
```sh
```
> Update PyPi user guide for auto-server-patcher & tabular view of arguments.

- requirements.txt
- securetea/lib/osint/osint.py
- securetea/lib/osint/osint_logger.py
- test/test_osint.py
**READY**
**Open Source Intelligence (OSINT)**
**Overview**
Use the power of open source tools to gather information about any attacker/intrusion as gathered by log monitoring, IDS/IPS & firewall & generate CSV report.
**Features:**
- WHOIS​ lookup
- Reverse DNS​ lookup
- Geo​ lookup
- Generate ​ CSV​ report
Since, this OSINT tool will be connected later on to IDS, Firewall and Server Log Monitor, it is not connected to the core program, hence not accessible by any arguments, only internally accessed by the above mentioned modules.
branch | PR
Outline the steps to test or …
> Feature: OSINT analysis about the IP address

- requirements.txt
- securetea.conf
- securetea/__init__.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/core.py
- securetea/lib/__init__.py
- securetea/lib/iot/__init__.py
- securetea/lib/iot/iot_checker.py
- securetea/lib/iot/iot_logger.py
- test/test_iot_checker.py
**READY**
“Shodan ​ a search engine which collects the information about all IPv4 and IPv6 devices connected to the internet and gives us the ability to search devices using filters that can be very sophisticated.”​ ​ (source:​ ​https://resources.infosecinstitute.com/shodan-iot-problem/#gref​)
In short, Shodan is a search engine for IoT devices, that can index thousands of IoT devices connected to the internet. At times, this can be great for hackers trying to gain access to the device.
As a security feature, it would be good to stay out of Shodan search radar. It will good to check whether the IoT device is under the Shodan grid or not, if
yes, immediate action needs to be taken or else we are all fine!
**Features:**
1. Use public IP address of the device to check (if provided) else …
> Featrue: Check IoT device Security / Anonymity

- doc/en-US/user_guide.md
**READY**
Update user guide: Add AntiVirus docs.
branch | PR
```sh
```
> Update user guide: Add AntiVirus docs

- doc/en-US/user_guide_pypi.md
**READY**
PyPi docs: Add AntiVirus details.
branch | PR
```sh
```
> PyPi docs: Add AntiVirus details

- doc/en-US/user_guide.md
**READY**
User docs: Add web deface detection docs.
branch | PR
```sh
```
> User docs: Add web deface detection docs

- doc/en-US/user_guide_pypi.md
**READY**
PyPi docs: Add web deface details.
branch | PR
```sh
```
> PyPi docs: Add web deface details

- README.md
**READY**
Fix all contributors badge.
branch | PR
```sh
```
1. `README.md`
> Fix all contributors badge

- doc/en-US/user_guide.md
**READY**
Add IoT Anonymity Checker docs.
branch | PR
```sh
```
1. 
*
> User docs: Add IoT Anonymity Checker docs

- doc/en-US/dev_guide.md
**READY**
Update roadmap.
branch | PR
```sh
```
1. `dev_guide.md`
> Dev docs: Update roadmap

- doc/en-US/user_guide_pypi.md
**READY**
Add IoT checker docs.
branch | PR
```sh
```
> PyPi docs: Add IoT checker docs

- securetea/args/arguments.py
**READY**
Update IoT checker args (help).
branch | PR
```sh
```
1. 
*
> Update IoT checker args

- setup.py
**READY**
Update setup.py for 1.5.1 release.
branch | PR
```sh
```
1. `setup.py`
> Update setup.py for 1.5.1 release

- doc/en-US/user_guide.md
**READY**
Add OSINT feature details.
branch | PR
```sh
```
> User docs: Add OSINT feature details

- doc/en-US/user_guide_pypi.md
**READY**
Add OSINT details.
branch | PR
```sh
```
> PyPi: Add OSINT details

- doc/en-US/dev_guide.md
**READY**
- Add Server log docs.
- Add AntiVirus docs.
- Add Web deface docs.
- Add Auto-Server-Patcher docs.
branch | PR
```sh
```
1. `dev_guide.md`
> Update developer docs

- securetea/lib/firewall/packet_filter.py
**READY**
Connect OSINT with Firewall to generate CSV report of the blocked IP address.
branch | PR
```sh
```
1. `packet_filter.py`
> Elemental connection: Connect OSINT with Firewall

- securetea/lib/ids/r2l_rules/ping_of_death.py
- securetea/lib/ids/recon_attack.py
- test/test_ping_of_death.py
- test/test_recon_attack.py
**READY**
Elemental connection: Connect OSINT with IDS to generate CSV report of the malicious IP address.
branch | PR
```sh
```
1. SecureTea IDS and OSINT connection
> Elemental connection: Connect OSINT with IDS

- securetea/lib/log_monitor/system_log/port_scan.py
- securetea/lib/log_monitor/system_log/ssh_login.py
- test/test_port_scan.py
- test/test_ssh_login.py
**READY**
Connect system log monitor with OSINT to generate CSV report about the malicious IP address.
branch | PR
```sh
```
1. 
*
> Elemental connection: Connect system log monitor with OSINT

- securetea/lib/log_monitor/server_log/detect/attacks/ddos.py
- securetea/lib/log_monitor/server_log/detect/attacks/lfi.py
- securetea/lib/log_monitor/server_log/detect/attacks/sqli.py
- securetea/lib/log_monitor/server_log/detect/attacks/web_shell.py
- securetea/lib/log_monitor/server_log/detect/attacks/xss.py
- securetea/lib/log_monitor/server_log/detect/recon/fuzzer.py
- securetea/lib/log_monitor/server_log/detect/recon/port_scan.py
- securetea/lib/log_monitor/server_log/detect/recon/spider.py
- test/test_fuzzer.py
- test/test_lfi.py
- test/test_port_scan0.py
- test/test_server_ddos.py
- test/test_spider.py
- test/test_sqli.py
- test/test_web_shell.py
- test/test_xss.py
**READY**
Connect server log monitor to OSINT to generate CSV report about malicious IP address.
branch | PR
```sh
```
1. SecureTea Server Log Monitor and OSINT connection
> Elemental connection: Connect server log monitor to OSINT

- securetea/common.py
- securetea/lib/firewall/engine.py
- securetea/lib/firewall/packet_filter.py
- securetea/lib/firewall/utils.py
- securetea/lib/ids/r2l_rules/ping_of_death.py
- securetea/lib/ids/recon_attack.py
- test/test_common.py
- test/test_engine.py
- test/test_packet_filter.py
- test/test_ping_of_death.py
- test/test_recon_attack.py
- test/test_utils.py
**READY**
Make Firewall smart: Learn bad IP address from IDS.
branch | PR
```sh
```
1. SecureTea Firewall
2. SecureTea IDS
> Make Firewall smart: Learn bad IP address from IDS

- doc/en-US/dev_guide.md
**READY**
Fix contents spacing to improve readability and match the current doc formatting standards..
branch | PR
```sh
```
1. `dev_guide,md`
> Fix contents spacing to improve readability and match the current doc formatting standards.

- securetea/lib/log_monitor/server_log/detect/attacks/ddos.py
- securetea/lib/log_monitor/server_log/detect/attacks/lfi.py
- securetea/lib/log_monitor/server_log/detect/attacks/sqli.py
- securetea/lib/log_monitor/server_log/detect/attacks/web_shell.py
- securetea/lib/log_monitor/server_log/detect/attacks/xss.py
- securetea/lib/log_monitor/server_log/detect/recon/fuzzer.py
- securetea/lib/log_monitor/server_log/detect/recon/port_scan.py
- securetea/lib/log_monitor/server_log/detect/recon/spider.py
- test/test_fuzzer.py
- test/test_lfi.py
- test/test_port_scan0.py
- test/test_server_ddos.py
- test/test_spider.py
- test/test_sqli.py
- test/test_web_shell.py
- test/test_xss.py
**READY**
Make Firewall smart: Learn bad IP address from Real-time Server Log Monitor.
branch | PR
```sh
```
1. SecureTea Server Log Monitor
> Make Firewall smart: Learn bad IP address from Real-time Server Log Monitor

- securetea/__init__.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/core.py
- securetea/modes/__init__.py
- securetea/modes/server_mode.py
**READY**
SecureTea Server mode, this mode includes the running of the following modules:
1. Firewall
2. Server Log Monitor
3. AntiVirus
4. System Log Monitor
5. Intrusion Detection System (IDS)
6. Auto Server Patcher
7. Web Deface Detection
The mode can be easily started using the args `--server-mode`, the following command is what follows:
1. Normal
`sudo SecureTea.py --server-mode`
2. Debug / Developer
`sudo SecureTea.py --debug --server-mode`
Upon this, it will ask whether to load the previously saved configurations or enter a new one. Choosing to go with a new configuration will start an interactive setup of the respected modules. Also, user can skip any module among the above 7 modules.
It makes a lot easier to configure SecureTea, with server mode they can easily secure their …
> Feature: Introduce SecureTea server mode

- securetea/__init__.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/core.py
- securetea/modes/__init__.py
- securetea/modes/system_mode.py
**READY**
SecureTea System mode, this mode includes the running of the following modules:
1. Firewall
2. AntiVirus
3. System Log Monitor
4. Intrusion Detection System (IDS)
The mode can be easily started using the args `--system-mode`, the following command is what follows:
1. Normal
`sudo SecureTea.py --system-mode`
2. Debug / Developer
`sudo SecureTea.py --debug --system-mode`
Upon this, it will ask whether to load the previously saved configurations or enter a new one. Choosing to go with a new configuration will start an interactive setup of the respected modules. Also, user can skip any module among the above 4 modules.
It makes a lot easier to configure SecureTea, with system mode they can easily secure their PC / Laptop / other systems. They don't need to bother about the various …
> Feature: Introduce SecureTea System mode

- securetea/lib/iot/iot_checker.py
**READY**
Fix: Invalid Shodan API key blocks API Key attribute declaration.
branch | PR
```sh
```
1. `iot_checker.py`
> Fix #191: Bug: Invalid Shodan API key blocks API Key attribute declaration

- setup.py
**READY**
Fix #196: Instruct setup.py to copy configuration file.
branch | PR
```sh
```
1. `setup.py`
> Fix #196: Instruct setup.py to copy configuration file

- securetea/args/arguments.py
**READY**
Make modes mutually exclusive, i.e. at a time user can only run Server, System or IoT mode. Not all at once.
branch | PR
```sh
```
1. `arguments.py`
> Make modes mutually exclusive

- doc/en-US/user_guide.md
**READY**
User docs: Add server mode details.
branch | PR
```sh
```
> User docs: Add server mode details

- doc/en-US/user_guide_pypi.md
**READY**
PyPi docs: Add server mode details.
branch | PR
```sh
```
> PyPi docs: Add server mode details

- securetea/core.py
**READY**
Fix #202: Look for appropriate keys.
branch | PR
```sh
```
1. `core.py`
> Fix #202: Look for appropriate keys

- gui/src/app/app-routing.module.ts
- gui/src/app/app.module.ts
- gui/src/app/login/login.component.html
- gui/src/app/login/login.component.spec.ts
- gui/src/app/login/login.component.ts
- gui/src/app/sidebar/sidebar.component.html
- monitor.py
**READY**
**Feature:** Add last login details to GUI dashboard.
**Columns:**
Username | Date | Status
---------------|--------|---------
Name of the user | Date of last login | Running or down?
**Component preview:**
**Side-bar icon preview:**
branch | PR
```sh
```
1. Last login GUI
> Feature: Add last login details to GUI dashboard

- securetea/lib/ids/r2l_rules/arp_spoof.py
- securetea/lib/ids/r2l_rules/cam_attack.py
- securetea/lib/ids/r2l_rules/ddos.py
- securetea/lib/ids/r2l_rules/dhcp.py
- securetea/lib/ids/r2l_rules/land_attack.py
- securetea/lib/ids/r2l_rules/ping_of_death.py
- securetea/lib/ids/r2l_rules/r2l_engine.py
- securetea/lib/ids/r2l_rules/syn_flood.py
- securetea/lib/ids/r2l_rules/wireless/deauth.py
- securetea/lib/ids/r2l_rules/wireless/fake_access.py
- securetea/lib/ids/r2l_rules/wireless/hidden_node.py
- securetea/lib/ids/r2l_rules/wireless/ssid_spoof.py
**READY**
Fixes #207 - Add missing UTF-8 module encoding definition.
branch | PR
```sh
```
1. IDS R2L Modules
> Fix #207 - Add missing UTF-8 module encoding definition

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
**READY**
GUI: Add Gmail notification text fields.
**Work done:**
- Made PEP-8 changes
- Added relevant comments
- Reduced border size to improve visual elegance
- Added text fields for Gmail notification arguments (data)
**Before filling the details:**
**After filling the details:**
branch | PR
```sh
```
1. Gmail Notification GUI
> GUI: Add Gmail notification text fields

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
**READY**
- GUI: Add antivirus configurations fields.
- Refactored a bit
- Added comments
branch | PR
```sh
```
1. AntiVirus GUI
> GUI: Add antivirus configuration fields

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
- securetea/lib/auto_server_patcher/secureTeaServerPatcher.py
**READY**
GUI: Add GUI configuration fields for Auto Server Patcher.
**Preview:**
branch | PR
```sh
```
1. GUI - Auto Server Patcher
> GUI: Add GUI configuration fields for Auto Server Patcher

- doc/en-US/dev_guide.md
**READY**
Fix mode diagram missing link due to forked branch deletion.
branch | PR
```sh
```
1. `dev_guide.md`
> Dev docs: Fix mode diagram missing link due to forked branch deletion

- doc/en-US/user_guide.md
**READY**
User docs: Add system mode details.
branch | PR
```sh
```
> User docs: Add system mode details

- doc/en-US/user_guide_pypi.md
**READY**
PyPi docs: Add system mode details.
branch | PR
```sh
```
> PyPi docs: Add system mode details

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
**READY**
GUI: Add GUI for system log monitor.
- System Log Monitor needs no configuration parameters. It is self adjusting based on the environment system it is running.
branch | PR
**Preview:**
```sh
```
1. GUI -  System Log Monitor
> GUI: Add GUI for system log monitor

- doc/en-US/user_guide.md
**READY**
User docs: Add IoT mode details.
branch | PR
```sh
```
> User docs: Add IoT mode details

- doc/en-US/user_guide_pypi.md
**READY**
PyPi docs: Add IoT mode details.
branch | PR
```sh
```
> PyPi docs: Add IoT mode details

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
- securetea/args/args_helper.py
**READY**
GUI: Add Firewall configuration fields.
**Previews:**
branch | PR
```sh
```
1. Firewall GUI
> GUI: Add Firewall configuration fields

- doc/en-US/user_guide.md
**READY**
User docs: Provide support for technical jargon to improve user experience.
- Added descriptive hyper-link for defining what are interfaces
- Added description related to IDS threshold
branch | PR
```sh
```
> User docs: Provide support for technical jargon to improve user experience

- doc/en-US/user_guide_pypi.md
**READY**
PyPi docs: Provide support for technical jargon to improve user experience.
- Added descriptive hyper-link for defining what are interfaces
- Added description related to IDS threshold
branch | PR
```sh
```
> PyPi docs: Provide support for technical jargon to improve user experience

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
**READY**
GUI: Add server log monitor configuration fields.
**Previews:**
branch | PR
```sh
```
1. Server Log Monitor GUI
> GUI: Add server log monitor configuration fields

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/lib/ids/recon_attack.py
- securetea/lib/ids/secureTeaIDS.py
**READY**
GUI: Add Intrusion Detection System configuration fields.
**Previews:**
branch | PR
```sh
```
1. Intrusion Detection System GUI
> GUI: Add Intrusion Detection System configuration fields

- README.md
**READY**
Update README with the requested changes as per comment on the PR #222.
The following changes have been made:
- Removed pre-requisites
- Changes made as per the review comment
- Snipped unnecessary details to de-crowd readme
branch | PR
```sh
```
1.  `README.md`
> Update README with the requested changes

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
**READY**
GUI: Add Local Web Deface Detection & Prevention System configuration fields.
**Previews:**
branch | PR
```sh
```
1. Local Web Deface Detection & Prevention System
> GUI: Add Local Web Deface Detection & Prevention System configuration fields

- securetea/args/args_helper.py
**READY**
Collect network interface name before process division to avoid screen locking & base-10 error.
branch | PR
```sh
```
1. `args_helper.py`
> Collect network interface name before process division to avoid screen locking & base-10 error

- requirements.txt
- securetea/args/args_helper.py
- securetea/lib/firewall/utils.py
**READY**
Fix #229
branch | PR
```sh
```
> Fix #229 - Restore Python 2 support for input

- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- monitor.py
**READY**
GUI: Add IoT Anonymity Checker  & Insecure Headers configuration fields.
**Previews:**
branch | PR
```sh
```
1. GUI: Add IoT Anonymity Checker  & Insecure Headers configuration fields
> GUI: Add IoT Anonymity Checker  & Insecure Headers configuration fields

- securetea/lib/ids/r2l_rules/wireless/ssid_spoof.py
**READY**
End SSID spoof scanning loop when scanning not supported by the interface & safely log the message.
branch | PR
```sh
```
> End SSID spoof scanning loop when scanning not supported by the interface & safely log the message

- doc/en-US/web_https.md
**READY**
**Create guide for setting up local web serving over HTTPS:** Help user encrypt their SecureTea web serving using Open SSL.
branch | PR
```sh
```
1. `web_https.md`
> Create guide for setting up local web serving over HTTPS

- doc/en-US/user_guide_pypi.md
**READY**
Update user guide (PyPi) to latest.
- Connected securing local web server over HTTPS docs to user guide
- Added new dashboard images
- Corrected installation commands
- Removed the under development status
- Added new introduction
branch | PR
```sh
```
> Update PyPi docs to latest

- MANIFEST.in
- securetea/__init__.py
- securetea/args/__init__.py
- securetea/args/args_helper.py
- securetea/args/config.py
- securetea/entry_points/__init__.py
- securetea/entry_points/iot_ep.py
- securetea/entry_points/securetea_core_ep.py
- securetea/entry_points/server_ep.py
- securetea/entry_points/system_ep.py
- securetea/lib/antivirus/secureTeaAntiVirus.py
- securetea/lib/auto_server_patcher/installer.py
- securetea/lib/auto_server_patcher/patcher.py
- securetea/lib/log_monitor/server_log/detect/attacks/lfi.py
- securetea/lib/log_monitor/server_log/detect/attacks/sqli.py
- securetea/lib/log_monitor/server_log/detect/attacks/web_shell.py
- securetea/lib/log_monitor/server_log/detect/attacks/xss.py
- securetea/lib/log_monitor/server_log/detect/recon/port_scan.py
- securetea/lib/log_monitor/server_log/detect/recon/spider.py
- securetea/lib/log_monitor/system_log/harmful_root_command.py
- securetea/lib/web_deface/web_deface_engine.py
- securetea/modes/server_mode.py
- setup.py
- test/test_lfi.py
- test/test_port_scan0.py
- test/test_spider.py
- test/test_sqli.py
- test/test_web_shell.py
- test/test_xss.py
**READY**
Update setup.py for v2.0 release.
**Work done:**
- User can run SecureTea in **4 ways**:
1. `sudo securetea` -> Use any integration as an argument.
For example: `sudo securetea --firewall` will start Firewall only & so on.
2. Modes:
a. `sudo securetea-server` -> This will start SecureTea in server mode.
b. `sudo securetea-system` -> This will start SecureTea in system mode.
c. `sudo securetea-iot` -> This will start SecureTea in IoT mode.
3. For development purpose:
- Use the normal method: `sudo python SecureTea.py`
branch | PR
Outline the steps to test or reproduce …
> Update setup.py for v2.0 release

- README.md
- setup.py
**IN DEVELOPMENT/HOLD**
Updates in setup.py.
> Cleanup setup.py for Next release

- setup.py
**READY**
Update setup.py for v2.1 release.
**Changes made:**
- Moved the redundant requirements in extras to `install_requires`.
- Corrected the version number
- Updated the `extras_require`.
**Note**: Server & System mode share the same amount of dependencies need, but still they have two different list defined for them, I think it will be a good practice to keep separate dependency list for them even though they are same, because in near future the scenario may change.
branch | PR
```sh
git checkout …
```
> Update setup.py for v2.1 release

- .gitignore
- Dockerfile
- README.md
- doc/en-US/dev_guide.md
[issue](https://github.com/OWASP/SecureTea-Project/issues/241)
Added development Dockerfile with python3, nodejs and a code server running inside it.
- [-] Documentation
See updated README.md
Development Experience
Containerization
> Containerized Dev Environment

- setup.py
- test/test_monitor.py
**READY**
Fixes [test case](https://github.com/OWASP/SecureTea-Project/blob/master/test/test_monitor.py)
Make sure unittest/pytest is installed
```sh
git clone https://github.com/OWASP/SecureTea-Project.git
cd SecureTea-Project
python3 -m virtualenv sectest
source sectest/bin/activate
cp SecreTea.py ~
cd
pip install git+https://github.com/OWASP/SecureTea-Project.git
python3 SecureTea.py
```
```sh
git clone https://github.com/OWASP/SecureTea-Project.git
cd SecureTea-Project
python3 -m pytest test/test_monitor.py
```
* pip install
* testing
> Fixing failed test case, pip install

- .github/workflows/ubuntubuild.yml
- setup_debian.py
**READY**
Added a github action to release .deb
Copy the workflow to your securetea repo and push it to check if it works.
* Build
> Added github action

- setup.py
- setup_debian.py
**READY**
Update version for release
* setup.py
* setup_debian.py
> Version update

- .github/workflows/ubuntubuild.yml
**READY**
Fix for failing github action
* Github action
> Update version of svenstaro release action

- doc/en-US/user_guide.md
**READY**
Add installation guide to README
> README updates

- ServerApp/app/__init__.py
- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- securetea.conf
- securetea/__init__.py
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/args/config.py
- securetea/configurations.py
- securetea/core.py
- securetea/lib/__init__.py
- securetea/lib/notifs/__init__.py
- securetea/lib/notifs/secureTeaWhatsapp.py
- test/test_secureTeaWhatsapp.py
**READY**
Whatsapp Integration using Twilio WhatsApp sandbox.
> Whatsapp Integration

- doc/en-US/user_guide.md
- gui/src/app/security/security.component.ts
**READY**
This PR fixes #271 
branch | PR
```sh
```
1. 
*  GUI
> Fix For Sweetalert

- doc/Integration_list/List_integration.md
- doc/en-US/dev_guide.md
- doc/en-US/user_guide.md
- doc/en-US/user_guide_pypi.md
- securetea/lib/firewall/README.md
**READY**
Documentation for setting up Whatsapp Integration.
> Documentation for Whatsapp Integration

- .github/workflows/ubuntubuild.yml
**READY**
Possible fix for workflow failure.
* .github/workflows/ubuntubuild.yml
> Workflow Fix

- ServerApp/requirements.txt
- gui/package-lock.json
- securetea.conf
- securetea/__init__.py
- securetea/core.py
- securetea/lib/__init__.py
- securetea/lib/ids/__init__.py
- securetea/lib/ids/r2l_rules/__init__.py
- securetea/lib/ids/r2l_rules/bgp_abuse.py
- securetea/lib/ids/r2l_rules/dns_amp.py
- securetea/lib/ids/r2l_rules/r2l_engine.py
- test/test_bgp_abuse.py
- test/test_dns_amp.py
**READY**
1.Added DNS Amplification detection and test modules.
2.Added BGP Abuse detection and test modules.
1.  sudo python3 SecureTea.py --ids
2. sudo python3 -m unittest
* IDS:  Added DNS Amplification Detection Module and BGP Abuse Detection Module.
> New Attack Detection Modules for IDS 

- ServerApp/requirements.txt
- gui/package-lock.json
- securetea.conf
- securetea/core.py
**READY**
Earlier this error was being faced
GET /socket.io/?EIO=3&transport=polling&t=MniHjPM HTTP/1.1
when using the flask server due to wrong or absent version of python modules that are now added.
> Fix for socketio error

- securetea/__init__.py
- securetea/lib/__init__.py
- securetea/lib/web_deface/__init__.py
- securetea/lib/web_deface/backup.py
- securetea/lib/web_deface/config/signatures.txt
- securetea/lib/web_deface/monitor.py
- securetea/lib/web_deface/signature_detection.py
**READY**
Signature-based defacement attack detection.
* securetea/lib/web_deface/
> Signature Based Defacement detector

- securetea/args/args_helper.py
- securetea/lib/log_monitor/system_log/utils.py
- securetea/lib/waf/Server/reqHandler.py
- securetea/lib/waf/Server/requester.py
- securetea/lib/waf/Server/server.py
- securetea/modes/server_mode.py
READY
Error fix for Dist attribute not found in platform and added WAF to server mode.
* /secureTea/lib
> Fix error in Server Mode

- doc/en-US/user_guide.md
- requirements.txt
- securetea.conf
- securetea/args/args_helper.py
- securetea/args/arguments.py
- securetea/lib/waf/Server/SecureTeaWaf.py
- securetea/lib/waf/Server/classifier.py
- securetea/lib/waf/Server/reqHandler.py
- securetea/lib/waf/Server/requester.py
- securetea/lib/waf/Server/server.py
* READY
The WAF is now updated to run along with nginx reverse proxy .
* secureTea/lib/waf
* secureTea/args
> Updated WAF to work with nginx

- doc/en-US/dev_guide.md
- doc/en-US/user_guide.md
**READY**
Additional instruction and information in User and Developer Documentation.
@adeyosemanputra 
* user_guide.md
* dev_guide.md
> Documentation for IDS, Web Deface Module

- ServerApp/app/__init__.py
- gui/src/app/security/security.component.html
- gui/src/app/security/security.component.ts
- securetea/lib/web_deface/config/dataset.csv
- securetea/lib/web_deface/model.py
WAF can be run from the GUI web interface from now.
@adeyosemanputra @rejahrehim
> GUI support Added for WAF

- securetea/args/args_helper.py
- securetea/args/config.py
- securetea/lib/waf/Server/SecureTeaWaf.py
- securetea/lib/waf/Server/WafLogger.py
- securetea/lib/waf/Server/__init__.py
- securetea/lib/waf/Server/reqHandler.py
* READY
WAF logs can be accessed in the location /etc/securetea/waf.log
.securetea/lib/waf
> Added WAF logger

- .travis.yml
- securetea/lib/ids/r2l_rules/dns_amp.py
- test/test_dns_amp.py
**READY**
Fixed error in Travis build. @adeyosemanputra
> Update .travis.yml to fix the travis build

- doc/en-US/user_guide.md
**READY*
Inserted Demo Videos in the Documentation
@adeyosemanputra
> Inserted Demo Videos in the Documentation

- requirements.txt
Fixing Travis
@adeyosemanputra
> Fixing Travis Build

- doc/en-US/user_guide.md
**READY**
Documentation Change for malware analysis
#323
> Documentation Change for malware analysis

- README.md
- doc/en-US/user_guide.md
**READY**
- Updated `readme.md` with link to Malware Analysis
- Added gifs to `doc/en-US/user_guide.md`
#324
> Added GIF to docs for Malware Analysis

- doc/en-US/dev_guide.md
**READY**
- Included a complete instruction manual for anyone who wants to include a new module into the main CLI
> instructions for new devs to integrate new modules

- securetea/args/config.py
- securetea/lib/notifs/secureTeaMalwareAnalysis.py
**READY**
- Updated API Key checking in MalwareAnalysis
- Added color coding for easy error/warning identification
- Changed config.py
`/securetea/lib/notifs/secureTeaMalwareAnalysis.py`
`securetea/args/config.py`
> updated Logic and UI/UX

- README.md
This PR aims at fixing the commands and fixes #329 
branch | PR
Just run the currently given commands  under installation guide.
```sh
```
1. 
installation of the project
*
>  fixed the commands for installation 

- securetea/args/args_helper.py
- securetea/entry_points/iot_ep.py
- securetea/entry_points/server_ep.py
- securetea/entry_points/system_ep.py
This PR resolves #332 
branch | PR
```sh
```
1. 
The very start of the application
*
> removed unnecessary conditions in the code and added the instruction to quit the application

- doc/en-US/user_guide.md
- gui/src/app/header/header.component.html
…nitor
In the user guide, there are 2 sections indicating the instructions for Setting up Server Log Monitor:
1. https://github.com/OWASP/SecureTea-Project/blob/master/doc/en-US/user_guide.md#setting-up-server-log-monitor-1
2. https://github.com/OWASP/SecureTea-Project/blob/master/doc/en-US/user_guide.md#setting-up-server-log-monitor
I removed one of those to make the documentation clearer.
I also removed the unnecessary menu icon present on the web GUI. 
branch | PR
```sh
git …
```
> removed the repeating instructions regarding the server log

- securetea/lib/antivirus/secureTeaAntiVirus.py
- securetea/lib/log_monitor/server_log/utils.py
- securetea/lib/log_monitor/system_log/harmful_root_command.py
- securetea/lib/waf/Server/SecureTeaWaf.py
- securetea/lib/waf/Server/WafLogger.py
- securetea/lib/waf/Server/reqHandler.py
- securetea/lib/waf/Server/requester.py
- securetea/lib/web_deface/config/dataset.csv
**READY**
- Cleaned up errors in lib
> Cleaning up errors

- ServerApp/app/__init__.py
issue #387 
Corrected for response code for check_auth fail and internal server error
> Response code corrected

- ServerApp/app/__init__.py
**READY**
Solves issue: #394 
changed key of info in cpuinfo
> added _raw in key of cpuinfo

- gui/src/app/header/header.component.css
- gui/src/app/header/header.component.html
- gui/src/assets/css/style.css
> Fixed the dashboard CSS bug

- gui/src/app/app-routing.module.ts
- gui/src/app/app.module.ts
- gui/src/app/ids/ids.component.html
- gui/src/app/ids/ids.component.spec.ts
- gui/src/app/ids/ids.component.ts
- gui/src/app/sidebar/sidebar.component.html
- securetea/lib/ids/database.py
This adds new IDS ui to the dashboard to monitor detected intruders.
> Added UI for IDS and database setup
